### ISSUE TITLE
Player vs Computer Math.random() fix

### ISSUE THREAD

**Issue by atulmy** [atulmy/rps#11]

**Comment by swapnil0545** [comment]
What are the replication steps for this issue?

**Comment by atulmy** [comment]
The issue: As meteor maintains copy of mongodb data on client side (minimongo), Math.random() is actually executed on Client first and then again on Server. So the outcome of Math.random() being different on both side, whenever user chooses any object (say Paper), the computer selection will vary for that set. For a moment you can see computer selecting Rock but when the code is executed again on Server, it may chose something else.

Possible solution: Run Math.random() on client only and pass the value to server.

**Comment by hedcet** [comment]
Math.random() always give random output ??

**Comment by hedcet** [comment]
Meteor.call can reduce it to one

**Comment by atulmy** [comment]
@HedCET Yes, because it is executed twice :crying_cat_face:

**Comment by hedcet** [comment]
Can u point exact lines here

**Comment by atulmy** [comment]
@HedCET https://github.com/atulmy/rps/blob/master/both/collections/games.js#L125

The output of Math.floor(Math.random() \* (xmax + 1 - xmin) + xmin) is always within the range 0 to 2. Where 0 = 'rock', 1 = 'paper', 2 = 'scissors'

**Comment by hedcet** [comment]
move that to sever folder, solve the two time execution ?

**Comment by atulmy** [comment]
@HedCET this needs to be executed on both side. That solution wont work.
