### ISSUE TITLE
how u keep list of online users ?

### ISSUE THREAD

**Issue by hedcet** [atulmy/rps#6]
using this https://github.com/atulmy/rps/blob/master/client/subscribe/users.js#L1

**Comment by atulmy** [comment]
No, that is added only for testing purpose. Will be removed as users info is not required. User name is getting saved inside game document. 

There is no list of online users currently. Only online games are being shown. Using https://github.com/atulmy/rps/blob/master/both/schemas/games.js#L70 and https://github.com/atulmy/rps/blob/master/both/schemas/games.js#L74
